import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "@/components/navbar";
import Providers from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const authenticated = false;

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {authenticated ? (
            <>
              <Navbar />
              <div className="m-8">{children}</div>
              <Toaster />
            </>
          ) : (
            <>{children}</>
          )}
        </Providers>
      </body>
    </html>
  );
}
