name: E2E Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  ENV: e2e
  DATABASE_URL: postgresql://trainix:trainix@localhost:5433/trainix-e2e
  NEXT_PUBLIC_API_ENDPOINT: http://localhost:5000
  SALT_ROUNDS: 10
  ACCESS_TOKEN_SECRET: 4cc3ssT0k3nS3cr3t
  REFRESH_TOKEN_SECRET: R3fr3shT0K3nS3cr3t
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  PLAYWRIGHT_BROWSERS_PATH: 0

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4

      - name: "Install pnpm"
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        shell: bash
        run: pnpm install

      - name: Download Docker-Compose plugin
        shell: bash
        run: sudo curl -SL https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose

      - name: Make plugin executable
        shell: bash
        run: sudo chmod +x /usr/local/bin/docker-compose

      - name: Generate Prisma schema
        run: cd api && pnpm run prisma:generate

      - name: Install Playwright
        run: cd e2e && npx playwright install --with-deps
      - run: cd e2e && npx playwright install

      - name: Run tests
        run: pnpm run e2e:test
